apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.secrets }}
    {{ $k }}: {{ $v | b64enc }}
  {{- end }}