## @param mariadb.enabled Whether to deploy a mariadb server to satisfy the applications database requirements
## To use an external database set this to false and configure the externalDatabase parameters
##
enabled: true
## @param mariadb.architecture MariaDB architecture. Allowed values: `standalone` or `replication`
##
architecture: standalone
## MariaDB Authentication parameters
##
auth:
  ## @param mariadb.auth.rootPassword Password for the MariaDB `root` user
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mariadb#setting-the-root-password-on-first-run
  ##
  rootPassword: "FF"
  ## @param mariadb.auth.database Database name to create
  ## ref: https://github.com/bitnami/containers/blob/main/bitnami/mariadb/README.md#creating-a-database-on-first-run
  ##
  database: bash2js
  ## @param mariadb.auth.username Database user to create
  ## ref: https://github.com/bitnami/containers/blob/main/bitnami/mariadb/README.md#creating-a-database-user-on-first-run
  ##
  username: bash2js
  ## @param mariadb.auth.password Password for the database
  ##
  password: "passW0RD"
primary:
  ## Enable persistence using Persistent Volume Claims
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## @param mariadb.primary.persistence.enabled Enable database persistence using PVC
    ##
    enabled: true
    ## @param mariadb.primary.persistence.storageClass MariaDB primary persistent volume storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""
    ## @param mariadb.primary.persistence.accessModes PVC Access Modes for phpBB volume
    ##
    accessModes:
      - ReadWriteOnce
    ## @param mariadb.primary.persistence.size Database Persistent Volume Size
    ##
    size: 8Gi
    ## @param mariadb.primary.persistence.hostPath Host mount path for MariaDB volume
    ##
    hostPath: ""
    ## @param mariadb.primary.persistence.existingClaim Name of an existing `PersistentVolumeClaim` for MariaDB primary replicas
    ##
    existingClaim: ""
